name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
      
      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install valgrind
        run: sudo apt-get install -y valgrind libcunit1 libcunit1-dev

      - name: Run CMake consuming root CMakePresets.json
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'x64-debug'
            
      - name: List files in dir
        run: ls -all
        working-directory: '${{ github.workspace }}'
        
      - name: Build project
        run: make
        working-directory: '${{ github.workspace }}'
        
      - name: List files in dir
        run: ls -all
        working-directory: '${{ github.workspace }}'
      
      - name: Run tests
        run: valgrind '${{ github.workspace }}/CUnitRunner' -tool=memcheck --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no
