name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
      
      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install valgrind
        run: sudo apt-get install -y valgrind libcunit1 libcunit1-dev
      
      - name: Build project
        run: |
          cd '${{ github.workspace }}'
          ls -all
          cmake -G "Unix Makefiles" --preset x64-debug ./CMakeLists.txt
          ls -all
          make
          ls -all

      - name: Run tests
        run: valgrind CUnitRunner -tool=memcheck --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no
