name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y build-essential cmake valgrind libcunit1 libcunit1-dev make
      
      - name: Build project
        run: |
          cd '${{ github.workspace }}'
          ls -all
          cmake --preset x64-debug ./CMakeLists.txt
          ls -all
          make
          ls -all

      - name: Run tests
        run: valgrind CUnitRunner -tool=memcheck --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no
